FROM node:21

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV PRIVATE_KEY=xxxxxxxxxxxxxxx
ENV ORACLE_CONTRACT_ADDRESS="0x86Bf8ecF08a968c5A4B508289e28258B5eFE064D"
ENV PROVIDER_URL="https://rpc-1.testnet.japanopenchain.org:8545"
ENV MUFG_API="https://developer.api.bk.mufg.jp/btmu/corporation/trial/v1/accounts"
ENV MUFG_API_KEY=xxxxxxxxxxxxxxx
ENV API_URL="http://jpyn.net"

CMD ["npx", "ts-node", "jpynOracleClient.ts"]